Organizing Committee:
- Late Breaking Report Chair, IEEE International Conference on Robot & Human Interactive Communication (RO-MAN), South Korea, 2023
- Program Chair, Asian Conference on Computer Aided Surgery (ACCAS), Online, 2021
- Program Chair, Asian Conference on Computer Aided Surgery (ACCAS), Thailand, 2022
Editorial Advisory Board:
- The International Journal of Medical Robotics and Computer Assisted Surgery (IJMRCAS), (2023-04 – Current)
Reviewer:
- IEEE/ASME Transactions on Mechatronics (TMECH)
- IEEE Robotics and Automation Letters (RA-L)
- IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)
- IEEE International Conference on Robotics and Automation (ICRA)
- The International Journal of Medical Robotics and Computer Assisted Surgery (IJMRCAS)
- IEEE Transactions on Automation Science and Engineering (T-ASE)
Conference Assistant:
- IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), Daejeon, South Korea, 2016
Member:
- International dVRK (da Vinci Research Kit) community
- K-NOTES (The Korean NOTES Society)
